# Generated by Django 5.0 on 2024-01-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="last_edited_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата последнего редактирования"
            ),
        ),
    ]
