# Generated by Django 5.0 on 2024-01-15 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_options_alter_post_last_edited_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="last_edited_date",
            new_name="updated",
        ),
    ]
