# Generated by Django 5.0 on 2024-01-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_last_edited_date_post_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique=True, verbose_name="Slug"),
        ),
    ]
