# Generated by Django 5.0 on 2024-01-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Имейл"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "ind_number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="ИНН"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата внесения товара в базу"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="last_edited_date",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
