# Generated by Django 5.0 on 2024-01-30 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("last_edited_date", "name"),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
