# Generated by Django 5.0 on 2024-01-30 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-last_edited_date", "name"),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
